DECLARE @NUNOTA_PED INT, 
	@VLRNOTA_PED FLOAT, 
	@BASEICMS_PED FLOAT,
	@VLRICMS_PED FLOAT,
	@BASEIPI_PED FLOAT,
	@VLRIPI_PED FLOAT,
	@VLRDIFAL_PED FLOAT,
	@NUNOTA_NFE INT, 
	@VLRNOTA_NFE FLOAT, 
	@BASEICMS_NFE FLOAT,
	@VLRICMS_NFE FLOAT,
	@BASEIPI_NFE FLOAT,
	@VLRIPI_NFE FLOAT,
	@VLRDIFAL_NFE FLOAT,
	@VLRDESBO_NFE FLOAT,
	@VLRBAIX_NFE FLOAT,
	@VLRDESBO_PED FLOAT,
	@VLRBAIX_PED FLOAT


DECLARE BUSCAR_PEDIDOS CURSOR FOR 

SELECT CAB.NUNOTA,
	CAB.VLRNOTA,
	CAB.BASEICMS,
	CAB.VLRICMS,
	CAB.BASEIPI,
	CAB.VLRIPI,
	CAB.VLRICMSDIFALDEST
FROM TGFCAB CAB
WHERE NUNOTA IN (36263) 

OPEN BUSCAR_PEDIDOS

FETCH NEXT FROM BUSCAR_PEDIDOS INTO @NUNOTA_PED, @VLRNOTA_PED, @BASEICMS_PED, @VLRICMS_PED, @BASEIPI_PED, @VLRIPI_PED, @VLRDIFAL_PED

WHILE @@FETCH_STATUS = 0
BEGIN
	
	IF EXISTS(SELECT TOP 1 NUNOTA FROM TGFVAR WHERE NUNOTAORIG = @NUNOTA_PED)
	BEGIN

		SET @NUNOTA_NFE = (SELECT TOP 1 NUNOTA FROM TGFVAR WHERE NUNOTAORIG = @NUNOTA_PED)
		
		DECLARE BUSCAR_NOTA CURSOR FOR
			SELECT CAB.NUNOTA,
				CAB.VLRNOTA,
				CAB.BASEICMS,
				CAB.VLRICMS,
				CAB.BASEIPI,
				CAB.VLRIPI,
				CAB.VLRICMSDIFALDEST
			FROM TGFCAB CAB
			WHERE NUNOTA = @NUNOTA_NFE

		OPEN BUSCAR_NOTA

		FETCH NEXT FROM BUSCAR_NOTA INTO @NUNOTA_NFE, @VLRNOTA_NFE, @BASEICMS_NFE, @VLRICMS_NFE, @BASEIPI_NFE, @VLRIPI_NFE, @VLRDIFAL_NFE 
		
		WHILE @@FETCH_STATUS = 0
		BEGIN
			
			IF (@VLRNOTA_NFE <> @VLRNOTA_PED)
			BEGIN
				UPDATE TGFCAB SET VLRNOTA = @VLRNOTA_NFE WHERE NUNOTA = @NUNOTA_PED
			END

			IF (@BASEICMS_NFE <> @BASEICMS_PED)
			BEGIN
				UPDATE TGFCAB SET BASEICMS= @BASEICMS_NFE WHERE NUNOTA = @NUNOTA_PED
			END

			IF (@VLRICMS_NFE <> @VLRICMS_PED)
			BEGIN
				UPDATE TGFCAB SET VLRICMS = @VLRICMS_NFE WHERE NUNOTA = @NUNOTA_PED
			END

			IF (@BASEIPI_NFE <> @BASEICMS_PED)
			BEGIN
				UPDATE TGFCAB SET BASEIPI = @BASEIPI_NFE WHERE NUNOTA = @NUNOTA_PED
			END

			IF (@VLRIPI_NFE <> @VLRIPI_PED)
			BEGIN
				UPDATE TGFCAB SET VLRIPI = @VLRIPI_NFE WHERE NUNOTA = @NUNOTA_PED
			END
			
			IF (@VLRDIFAL_NFE <> @VLRDIFAL_PED)
			BEGIN
				UPDATE TGFCAB SET VLRICMSDIFALDEST = @VLRDIFAL_NFE WHERE NUNOTA = @NUNOTA_PED
			END

			IF EXISTS (SELECT NUFIN FROM TGFFIN WHERE NUNOTA = @NUNOTA_NFE)
			BEGIN

				DECLARE BUSCAR_FINANCEIRO_NFE CURSOR FOR
					
					SELECT VLRDESDOB,
						VLRBAIXA
					FROM TGFFIN
					WHERE NUNOTA = @NUNOTA_NFE
	
				OPEN BUSCAR_FINANCEIRO_NFE
	
				FETCH NEXT FROM BUSCAR_FINANCEIRO_NFE INTO @VLRDESBO_NFE, @VLRBAIX_NFE
	
				WHILE @@FETCH_STATUS = 0
				BEGIN
	
					IF EXISTS (SELECT NUFIN FROM TGFFIN WHERE NUNOTA = @NUNOTA_PED)
					BEGIN
					
						DECLARE BUSCAR_FINANCEIRO_PED CURSOR FOR
							
							SELECT VLRDESDOB,
								VLRBAIXA
							FROM TGFFIN
							WHERE NUNOTA = @NUNOTA_PED
	
						OPEN BUSCAR_FINANCEIRO_PED 
	
						FETCH NEXT FROM BUSCAR_FINANCEIRO_PED INTO @VLRDESBO_PED, @VLRBAIX_PED
	
						WHILE @@FETCH_STATUS = 0
						BEGIN
							
							IF (@VLRDESBO_NFE <> @VLRDESBO_PED)
							BEGIN
								UPDATE TGFFIN SET VLRDESDOB = @VLRDESBO_NFE WHERE NUNOTA = @NUNOTA_PED
							END
							
							IF EXISTS(SELECT VLRBAIXA FROM TGFFIN WHERE NUNOTA = @NUNOTA_NFE AND VLRBAIXA > 0 AND DHBAIXA IS NOT NULL)
							BEGIN

								IF (@VLRBAIX_NFE <> @VLRBAIX_PED)
								BEGIN
									UPDATE TGFFIN SET VLRBAIXA = @VLRBAIX_NFE WHERE NUNOTA = @NUNOTA_PED
								END

							END
	
						FETCH NEXT FROM BUSCAR_FINANCEIRO_PED INTO @VLRDESBO_PED, @VLRBAIX_PED
						END
						CLOSE BUSCAR_FINANCEIRO_PED
						DEALLOCATE BUSCAR_FINANCEIRO_PED

					END
					
				FETCH NEXT FROM BUSCAR_FINANCEIRO_NFE INTO @VLRDESBO_NFE, @VLRBAIX_NFE
				END
				CLOSE BUSCAR_FINANCEIRO_NFE
				DEALLOCATE BUSCAR_FINANCEIRO_NFE

			END
		
		FETCH NEXT FROM BUSCAR_NOTA INTO @NUNOTA_NFE, @VLRNOTA_NFE, @BASEICMS_NFE, @VLRICMS_NFE, @BASEIPI_NFE, @VLRIPI_NFE, @VLRDIFAL_NFE
		END
		CLOSE BUSCAR_NOTA
		DEALLOCATE BUSCAR_NOTA
	
	END

FETCH NEXT FROM BUSCAR_PEDIDOS INTO @NUNOTA_PED, @VLRNOTA_PED, @BASEICMS_PED, @VLRICMS_PED, @BASEIPI_PED, @VLRIPI_PED, @VLRDIFAL_PED
END
CLOSE BUSCAR_PEDIDOS
DEALLOCATE BUSCAR_PEDIDOS